events {}

http {
    # Define caminhos reais para arquivos físicos, ignorando os links do stdout
    access_log /var/log/nginx/custom_access.log;
    error_log /var/log/nginx/custom_error.log;

    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
}
